### ISSUE TITLE
SpringBoot 读取配置文件（application.yml）的属性值

### ISSUE THREAD

**Issue by clxering** [clxering/MyNotebook#27]
## 引入依赖
以下摘自 Spring 文档：[地址](https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor)

With Maven the dependency should be declared as optional, as shown in the following example:

```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-configuration-processor</artifactId>
	<optional>true</optional>
</dependency>
```

With Gradle 4.5 and earlier, the dependency should be declared in the compileOnly configuration, as shown in the following example:

```
dependencies {
	compileOnly "org.springframework.boot:spring-boot-configuration-processor"
}
```

With Gradle 4.6 and later, the dependency should be declared in the annotationProcessor configuration, as shown in the following example:
```
dependencies {
	annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
}
```

## 配置文件样例（application.yml）
```
testProps:
  stringSingle: stringSingle
  integerArray: 1,2,3,4,5
  objectList:
    - name: user1
    - value: userValue1
    - name: user2
    - value: userValue2
  stringList:
    - listValue1
    - listValue2
  maps:
    key1: mapValue1
    key2: mapValue2
```

可使用的类型
- 对象和Map：key: value 键值对形式，有两种写法：
```
# 第一种
props:
  UserName: Jackson
  UserAge: 22

# 第二种
student: {UserName: "Jackson",UserAge: 22}
```

- 数组：List、Set，也有两种写法：

```
# 第一种
UserName: 
  - Jackson
  - Mark

# 第二种
UserName: [Jackson,Mark]
```

注意事项：
- 属性和值的配置采用 key: value 键值对形式，冒号和值之间必须使用空格隔开
- 大小写敏感，可以使用驼峰命名
- 布尔类型必须小写（true 或 false）
- 字符串使用单引号在输出特殊字符时不会引发转义，比如，'\n' 输出的内容就是 \n，而使用双引号会引发转义，"\n" 输出内容是回车符。

## 接收配置信息
```
@Component
@ConfigurationProperties(prefix = "testprops")
public class TestProps {

    private String stringSingle;
    private Integer[] integerArray;
    private List<Map<String, String>> objectList = new ArrayList<>(); 
    private List<String> stringList = new ArrayList<>(); 
    private Map<String, String> maps = new HashMap<>(); 

    public String getStringSingle() {
        return stringSingle;
    }

    public void setStringSingle(String stringSingle) {
        this.stringSingle = stringSingle;
    }

    public Integer[] getIntegerArray() {
        return integerArray;
    }

    public void setIntegerArray(Integer[] integerArray) {
        this.integerArray = integerArray;
    }

    public List<Map<String, String>> getObjectList() {
        return objectList;
    }

    public List<String> getStringList() {
        return stringList;
    }

    public Map<String, String> getMaps() {
        return maps;
    }
}
```

注意事项：
- 配置文件中可以使用驼峰命名，但是 `@ConfigurationProperties(prefix = "testprops")` 的 prefix 必须全部使用小写
- 需要赋初值的数据类型，例如上述的 `String stringSingle` 以及 `Integer[] integerArray` 需要提供 set，其余情况只提供 get 即可

## 测试
```
@RunWith(SpringRunner.class)
@SpringBootTest
public class DemoApplicationTests {

    @Autowired
    public TestProps testProps;

    @Test
    public void contextLoads() {
        System.out.println("stringSingle: " + testProps.getStringSingle());
        System.out.println("integerArray: " + testProps.getIntegerArray());
        System.out.println("objectList: " + testProps.getObjectList());
        System.out.println("stringList: " + testProps.getStringList());
        System.out.println("maps: " + testProps.getMaps());
    }
}
```

测试结果：
```
stringSingle: stringSingle
integerArray: [Ljava.lang.Integer;@6b649efa
objectList: [{name=user1}, {value=userValue1}, {name=user2}, {value=userValue2}]
stringList: [listValue1, listValue2]
maps: {key1=mapValue1, key2=mapValue2}
```
